### ISSUE TITLE
Can't report multiple times on 1 device with different gles driver version ?

### ISSUE THREAD

**Issue by xDoge26** [SaschaWillems/glEsCapsViewer#4]
Hi, i have manually updated opengles driver but unlike vulkan caps viewer i cant upload my gpu info again

**Comment by SaschaWillems** [comment]
Thanks for reporting this. The database is currently experiencing problems, which may be the cause of your problem. I'm already investigating but haven't found out the problem yet.

**Comment by SaschaWillems** [comment]
It's indeed a problem with the app. After updating it to recent SDK versions, Android permits http calls. I'll have to release an updated version.

**Comment by SaschaWillems** [comment]
I have released an updated version to the store that fixes this problem.
